export interface Person {
  firstName: string;
  lastName: string;
  age: number;
  email: string;
  address: string;
}
export interface EPerson {
  firstName: string;
  lastName: string;
  email: string;
  education: string;
  age: string;
}

export const ManyPerson: EPerson[] = [
  {
    firstName: 'Nicole',
    lastName: 'Martinez',
    email: 'n_martinez19@ymail.com',
    education: 'Master’s degree',
    age: '20',
  },
  {
    firstName: 'Robert',
    lastName: 'Clark',
    email: 'r.clark@ymail.com',
    education: 'Associate degree',
    age: '27',
  },
  {
    firstName: 'Jeremy',
    lastName: 'Stewart',
    email: 'jeremystewart@outlook.com',
    education: 'Bachelor’s degree',
    age: '71',
  },
  {
    firstName: 'Kevin',
    lastName: 'Ward',
    email: 'k.ward@yahoo.com',
    education: 'Associate degree',
    age: '58',
  },
  {
    firstName: 'Tyler',
    lastName: 'Nelson',
    email: 'tylernelson@gmail.com',
    education: 'High school diploma or equivalent',
    age: '43',
  },
  {
    firstName: 'Christina',
    lastName: 'Murphy',
    email: 'christinamurphy@outlook.com',
    education: 'Master’s degree',
    age: '76',
  },
  {
    firstName: 'Julian',
    lastName: 'Martin',
    email: 'j_martin96@gmail.com',
    education: 'Doctoral degree',
    age: '51',
  },
  {
    firstName: 'Charles',
    lastName: 'Allen',
    email: 'c_e18@ymail.com',
    education: 'Master’s degree',
    age: '43',
  },
  {
    firstName: 'Evelyn',
    lastName: 'Washington',
    email: 'evelyn.washington77@rocketmail.com',
    education: 'Master’s degree',
    age: '77',
  },
  {
    firstName: 'Rachel',
    lastName: 'Bryant',
    email: 'rachel@rocketmail.com',
    education: 'Less than high school',
    age: '44',
  },
  {
    firstName: 'Ryan',
    lastName: 'Cooper',
    email: 'r_g_cooper@aol.com',
    education: 'Doctoral degree',
    age: '51',
  },
  {
    firstName: 'Jasmine',
    lastName: 'Baker',
    email: 'jasmine.m.baker@ymail.com',
    education: 'Doctoral degree',
    age: '71',
  },
  {
    firstName: 'Nathan',
    lastName: 'Powell',
    email: 'nathan.edward.powell@hotmail.com',
    education: 'Doctoral degree',
    age: '21',
  },
  {
    firstName: 'Lauren',
    lastName: 'Morris',
    email: 'lauren@live.com',
    education: 'Associate degree',
    age: '23',
  },
  {
    firstName: 'Sebastian',
    lastName: 'Peterson',
    email: 's_peterson@ymail.com',
    education: 'Master’s degree',
    age: '57',
  },
  {
    firstName: 'Christopher',
    lastName: 'Turner',
    email: 'cturner64@ymail.com',
    education: 'Master’s degree',
    age: '52',
  },
  {
    firstName: 'Nathan',
    lastName: 'Peterson',
    email: 'n_peterson@aol.com',
    education: 'Less than high school',
    age: '46',
  },
  {
    firstName: 'Joshua',
    lastName: 'Turner',
    email: 'joshua.turner@outlook.com',
    education: 'Bachelor’s degree',
    age: '44',
  },
  {
    firstName: 'Timothy',
    lastName: 'Green',
    email: 't_a_green89@rocketmail.com',
    education: 'Less than high school',
    age: '28',
  },
  {
    firstName: 'Courtney',
    lastName: 'Allen',
    email: 'c_m_allen@live.com',
    education: 'Some college, no degree',
    age: '32',
  },
  {
    firstName: 'Brian',
    lastName: 'Foster',
    email: 'brianfoster@aol.com',
    education: 'Associate degree',
    age: '23',
  },
  {
    firstName: 'Olivia',
    lastName: 'Cox',
    email: 'ojcox@yahoo.com',
    education: 'Associate degree',
    age: '55',
  },
  {
    firstName: 'Justin',
    lastName: 'Cox',
    email: 'justincox@aol.com',
    education: 'Associate degree',
    age: '75',
  },
  {
    firstName: 'Justin',
    lastName: 'Rogers',
    email: 'jerogers43@aol.com',
    education: 'Some college, no degree',
    age: '46',
  },
  {
    firstName: 'Tiffany',
    lastName: 'Lewis',
    email: 'tlewis@aol.com',
    education: 'Doctoral degree',
    age: '43',
  },
  {
    firstName: 'Amelia',
    lastName: 'Martin',
    email: 'a_r@aol.com',
    education: 'Less than high school',
    age: '75',
  },
  {
    firstName: 'Joshua',
    lastName: 'Miller',
    email: 'joshua_anthony@outlook.com',
    education: 'High school diploma or equivalent',
    age: '59',
  },
  {
    firstName: 'Austin',
    lastName: 'Thomas',
    email: 'a_e_thomas52@rocketmail.com',
    education: 'Associate degree',
    age: '34',
  },
  {
    firstName: 'Sofia',
    lastName: 'Moore',
    email: 's_moore@yahoo.com',
    education: 'Some college, no degree',
    age: '27',
  },
  {
    firstName: 'Kelsey',
    lastName: 'Thomas',
    email: 'kthomas@hotmail.com',
    education: 'Doctoral degree',
    age: '21',
  },
  {
    firstName: 'Matthew',
    lastName: 'Smith',
    email: 'matthew_smith@rocketmail.com',
    education: 'Some college, no degree',
    age: '55',
  },
  {
    firstName: 'Ryan',
    lastName: 'Long',
    email: 'ryan.long@live.com',
    education: 'High school diploma or equivalent',
    age: '50',
  },
  {
    firstName: 'Patrick',
    lastName: 'Adams',
    email: 'patrick.thomas.adams@yahoo.com',
    education: 'Bachelor’s degree',
    age: '60',
  },
  {
    firstName: 'Samantha',
    lastName: 'Carter',
    email: 'samantha_carter@yahoo.com',
    education: 'Associate degree',
    age: '63',
  },
  {
    firstName: 'Owen',
    lastName: 'Simmons',
    email: 'owen_simmons@ymail.com',
    education: 'Less than high school',
    age: '42',
  },
  {
    firstName: 'Christina',
    lastName: 'Lewis',
    email: 'christinamlewis@outlook.com',
    education: 'Doctoral degree',
    age: '57',
  },
  {
    firstName: 'Jonathan',
    lastName: 'Collins',
    email: 'jonathan@gmail.com',
    education: 'Less than high school',
    age: '20',
  },
  {
    firstName: 'Erin',
    lastName: 'Morgan',
    email: 'erin.morgan@ymail.com',
    education: 'Bachelor’s degree',
    age: '33',
  },
  {
    firstName: 'Aaron',
    lastName: 'Jackson',
    email: 'a_g_jackson@hotmail.com',
    education: 'Less than high school',
    age: '31',
  },
  {
    firstName: 'Tiffany',
    lastName: 'Taylor',
    email: 't_taylor@live.com',
    education: 'Master’s degree',
    age: '37',
  },
  {
    firstName: 'Jose',
    lastName: 'Ross',
    email: 'jose.ross@aol.com',
    education: 'Bachelor’s degree',
    age: '40',
  },
  {
    firstName: 'Victoria',
    lastName: 'Bennett',
    email: 'victoria_bennett@rocketmail.com',
    education: 'Doctoral degree',
    age: '39',
  },
  {
    firstName: 'Megan',
    lastName: 'Evans',
    email: 'meganjaneevans@aol.com',
    education: 'Some college, no degree',
    age: '70',
  },
  {
    firstName: 'Joseph',
    lastName: 'Kelly',
    email: 'j.e.kelly@aol.com',
    education: 'Master’s degree',
    age: '21',
  },
  {
    firstName: 'Eric',
    lastName: 'Cox',
    email: 'eric_r_cox@outlook.com',
    education: 'Less than high school',
    age: '36',
  },
  {
    firstName: 'David',
    lastName: 'Garcia',
    email: 'david_garcia2@ymail.com',
    education: 'Associate degree',
    age: '43',
  },
  {
    firstName: 'Kayla',
    lastName: 'Torres',
    email: 'krtorres@gmail.com',
    education: 'Associate degree',
    age: '56',
  },
  {
    firstName: 'Isabella',
    lastName: 'Morgan',
    email: 'isabella.faith.morgan@gmail.com',
    education: 'Doctoral degree',
    age: '19',
  },
  {
    firstName: 'Sofia',
    lastName: 'Green',
    email: 'sofia.green@ymail.com',
    education: 'Associate degree',
    age: '70',
  },
  {
    firstName: 'Eric',
    lastName: 'Wilson',
    email: 'ericalan@yahoo.com',
    education: 'Less than high school',
    age: '53',
  },
  {
    firstName: 'Ethan',
    lastName: 'Bennett',
    email: 'e_r_bennett@hotmail.com',
    education: 'Bachelor’s degree',
    age: '23',
  },
  {
    firstName: 'Emily',
    lastName: 'Patterson',
    email: 'emily@ymail.com',
    education: 'Some college, no degree',
    age: '55',
  },
  {
    firstName: 'Kaitlyn',
    lastName: 'Richardson',
    email: 'kaitlynrose23@aol.com',
    education: 'Master’s degree',
    age: '71',
  },
  {
    firstName: 'David',
    lastName: 'Campbell',
    email: 'david_lee_campbell@yahoo.com',
    education: 'Less than high school',
    age: '44',
  },
  {
    firstName: 'Haley',
    lastName: 'Collins',
    email: 'haley_r@hotmail.com',
    education: 'Some college, no degree',
    age: '40',
  },
  {
    firstName: 'Justin',
    lastName: 'Davis',
    email: 'j.t.davis@gmail.com',
    education: 'Bachelor’s degree',
    age: '46',
  },
  {
    firstName: 'Anna',
    lastName: 'Edwards',
    email: 'anna.m.edwards@aol.com',
    education: 'Doctoral degree',
    age: '57',
  },
  {
    firstName: 'Aiden',
    lastName: 'Jenkins',
    email: 'aiden.jenkins@hotmail.com',
    education: 'Bachelor’s degree',
    age: '46',
  },
  {
    firstName: 'Robert',
    lastName: 'Perry',
    email: 'robert.j.perry@aol.com',
    education: 'Master’s degree',
    age: '69',
  },
  {
    firstName: 'Zachary',
    lastName: 'James',
    email: 'zachary.g.james@live.com',
    education: 'Doctoral degree',
    age: '41',
  },
  {
    firstName: 'Amelia',
    lastName: 'Cox',
    email: 'amelia.cox@ymail.com',
    education: 'Less than high school',
    age: '64',
  },
  {
    firstName: 'Haley',
    lastName: 'Anderson',
    email: 'handerson1@ymail.com',
    education: 'Some college, no degree',
    age: '21',
  },
  {
    firstName: 'Kelsey',
    lastName: 'Bailey',
    email: 'k_k_bailey@gmail.com',
    education: 'Doctoral degree',
    age: '18',
  },
  {
    firstName: 'Megan',
    lastName: 'Lee',
    email: 'megandlee@ymail.com',
    education: 'Master’s degree',
    age: '39',
  },
  {
    firstName: 'Nicholas',
    lastName: 'Garcia',
    email: 'ngarcia24@live.com',
    education: 'Master’s degree',
    age: '50',
  },
  {
    firstName: 'Kayla',
    lastName: 'Wood',
    email: 'kayla.louise.wood@outlook.com',
    education: 'Bachelor’s degree',
    age: '21',
  },
  {
    firstName: 'William',
    lastName: 'Collins',
    email: 'william.collins@aol.com',
    education: 'Less than high school',
    age: '64',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Hernandez',
    email: 'j_m_hernandez@gmail.com',
    education: 'Doctoral degree',
    age: '70',
  },
  {
    firstName: 'Olivia',
    lastName: 'Morris',
    email: 'o.morris@outlook.com',
    education: 'Some college, no degree',
    age: '62',
  },
  {
    firstName: 'Ashley',
    lastName: 'Rodriguez',
    email: 'a_rodriguez@rocketmail.com',
    education: 'Doctoral degree',
    age: '52',
  },
  {
    firstName: 'John',
    lastName: 'Morris',
    email: 'john_morris@hotmail.com',
    education: 'Associate degree',
    age: '40',
  },
  {
    firstName: 'Chelsea',
    lastName: 'Roberts',
    email: 'c_f@outlook.com',
    education: 'High school diploma or equivalent',
    age: '53',
  },
  {
    firstName: 'Michael',
    lastName: 'Bennett',
    email: 'm.bennett@ymail.com',
    education: 'Doctoral degree',
    age: '63',
  },
  {
    firstName: 'Justin',
    lastName: 'Simmons',
    email: 'j_simmons25@live.com',
    education: 'Master’s degree',
    age: '35',
  },
  {
    firstName: 'Hannah',
    lastName: 'Stewart',
    email: 'hannah@hotmail.com',
    education: 'Less than high school',
    age: '29',
  },
  {
    firstName: 'Nathan',
    lastName: 'Kelly',
    email: 'n.kelly@outlook.com',
    education: 'Some college, no degree',
    age: '39',
  },
  {
    firstName: 'Emma',
    lastName: 'Wood',
    email: 'e_wood@aol.com',
    education: 'Doctoral degree',
    age: '20',
  },
  {
    firstName: 'James',
    lastName: 'Rodriguez',
    email: 'j_a_rodriguez83@hotmail.com',
    education: 'High school diploma or equivalent',
    age: '26',
  },
  {
    firstName: 'Sofia',
    lastName: 'Martinez',
    email: 'sofia_martinez62@ymail.com',
    education: 'Associate degree',
    age: '34',
  },
  {
    firstName: 'Kelsey',
    lastName: 'Howard',
    email: 'kelsey.howard@rocketmail.com',
    education: 'Master’s degree',
    age: '41',
  },
  {
    firstName: 'Jose',
    lastName: 'Kelly',
    email: 'j.kelly@gmail.com',
    education: 'Some college, no degree',
    age: '27',
  },
  {
    firstName: 'Justin',
    lastName: 'Flores',
    email: 'justin_flores99@yahoo.com',
    education: 'Less than high school',
    age: '64',
  },
  {
    firstName: 'Aubrey',
    lastName: 'Collins',
    email: 'aubreymcollins@hotmail.com',
    education: 'Less than high school',
    age: '56',
  },
  {
    firstName: 'Mateo',
    lastName: 'Simmons',
    email: 'm.r2@yahoo.com',
    education: 'High school diploma or equivalent',
    age: '56',
  },
  {
    firstName: 'Jonathan',
    lastName: 'Watson',
    email: 'jonathanawatson@outlook.com',
    education: 'Some college, no degree',
    age: '69',
  },
  {
    firstName: 'Dylan',
    lastName: 'Henderson',
    email: 'dylan_ray_henderson@aol.com',
    education: 'Bachelor’s degree',
    age: '54',
  },
  {
    firstName: 'Brittany',
    lastName: 'Stewart',
    email: 'brittany_stewart@rocketmail.com',
    education: 'Some college, no degree',
    age: '29',
  },
  {
    firstName: 'Joshua',
    lastName: 'Perez',
    email: 'jperez@ymail.com',
    education: 'Bachelor’s degree',
    age: '77',
  },
  {
    firstName: 'Victoria',
    lastName: 'Griffin',
    email: 'victoria.griffin@ymail.com',
    education: 'Bachelor’s degree',
    age: '39',
  },
  {
    firstName: 'Grace',
    lastName: 'Coleman',
    email: 'grace.coleman16@gmail.com',
    education: 'Less than high school',
    age: '69',
  },
  {
    firstName: 'Steven',
    lastName: 'Robinson',
    email: 'steven_lee_robinson@ymail.com',
    education: 'Bachelor’s degree',
    age: '68',
  },
  {
    firstName: 'Allison',
    lastName: 'Hall',
    email: 'allisonhall@gmail.com',
    education: 'High school diploma or equivalent',
    age: '49',
  },
  {
    firstName: 'Brianna',
    lastName: 'Cox',
    email: 'briannacox90@aol.com',
    education: 'High school diploma or equivalent',
    age: '63',
  },
  {
    firstName: 'Adam',
    lastName: 'Gray',
    email: 'a_r_gray@outlook.com',
    education: 'Associate degree',
    age: '71',
  },
  {
    firstName: 'Timothy',
    lastName: 'Parker',
    email: 'timothyrichard@yahoo.com',
    education: 'High school diploma or equivalent',
    age: '69',
  },
  {
    firstName: 'Samuel',
    lastName: 'Jackson',
    email: 's.jackson@outlook.com',
    education: 'Less than high school',
    age: '62',
  },
  {
    firstName: 'Claire',
    lastName: 'Harris',
    email: 'c_harris45@yahoo.com',
    education: 'Some college, no degree',
    age: '69',
  },
  {
    firstName: 'Adam',
    lastName: 'Wright',
    email: 'a_m_wright96@aol.com',
    education: 'Doctoral degree',
    age: '62',
  },
  {
    firstName: 'Henry',
    lastName: 'Cooper',
    email: 'henry@outlook.com',
    education: 'Less than high school',
    age: '32',
  },
  {
    firstName: 'Victoria',
    lastName: 'Campbell',
    email: 'victoria.l.campbell@ymail.com',
    education: 'Less than high school',
    age: '36',
  },
];
